### PR TITLE
reworded requirements

### PR DESCRIPTION
**Pull request by PF4Public**
It feels kind of vague, using _optional_ with already optional components.

### CODE REVIEW

**Comment by JerryCasiano** [comment]
Agreed.

There's a typo on line 190 though.

Additionally is missing an l.

But I think we should probably change that to something like

> If you wish to also build Google Fonts integration, which is enabled by default, the following libraries are required:

**Comment by PF4Public** [comment]
> Additionally is missing an l.

Whoops, slipped through my fingers.

> which is enabled by default

Riiight! I forgot about that.

> If you wish to also build Google Fonts integration, which is enabled by default, **the** following libraries are required:

Should _the_ be there?

**Comment by JerryCasiano** [comment]
> Should the be there?

So... I believe either way would be considered correct with _the_ being implied if you happen to leave it out.

**Comment by PF4Public** [comment]
I've just force-pushed. Feel free to merge if it's OK now.

**Comment by JerryCasiano** [comment]
Thanks

**Pull request merged**
